/**:
  robot_states_manager:
    ros__parameters:
      timer_frequency: 50.0
      ros_communication_timeout:
        availability: 2.0
        response: 1.0
      ros_plugin_libs:
        - call_trigger_service_bt_node
        - check_joy_msg_bt_node
        - dock_robot_bt_node
        - undock_robot_bt_node
