<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">

  <!-- wheel defining macro -->
  <xacro:macro name="wheel" params="wheel_config wheel_separation_x prefix">

    <xacro:if value="${prefix == 'fl'}">
      <xacro:property name="x" value="${wheel_separation_x/2.0}" />
      <xacro:property name="y" value="${wheel_config['wheel_separation']/2.0}" />
      <xacro:property name="inertia_y_offset" value="${wheel_config['inertia_y_offset']}" />
      <xacro:property name="fdir" value="1 -1 0" />
    </xacro:if>
    <xacro:if value="${prefix == 'fr'}">
      <xacro:property name="x" value="${wheel_separation_x/2.0}" />
      <xacro:property name="y" value="-${wheel_config['wheel_separation']/2.0}" />
      <xacro:property name="inertia_y_offset" value="${-wheel_config['inertia_y_offset']}" />
      <xacro:property name="fdir" value="1 1 0" />
    </xacro:if>
    <xacro:if value="${prefix == 'rl'}">
      <xacro:property name="x" value="-${wheel_separation_x/2.0}" />
      <xacro:property name="y" value="${wheel_config['wheel_separation']/2.0}" />
      <xacro:property name="inertia_y_offset" value="${wheel_config['inertia_y_offset']}" />
      <xacro:property name="fdir" value="1 1 0" />
    </xacro:if>
    <xacro:if value="${prefix == 'rr'}">
      <xacro:property name="x" value="-${wheel_separation_x/2.0}" />
      <xacro:property name="y" value="-${wheel_config['wheel_separation']/2.0}" />
      <xacro:property name="inertia_y_offset" value="${-wheel_config['inertia_y_offset']}" />
      <xacro:property name="fdir" value="1 -1 0" />
    </xacro:if>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <origin xyz="${x} ${y} 0.0" rpy="0.0 0.0 0.0" />
      <parent link="body_link" />
      <child link="${prefix}_wheel_link" />
      <axis xyz="0.0 1.0 0.0" />

      <limit effort="64.5" velocity="10.958" />
      <dynamics damping="0.01" friction="0.9" />
    </joint>

    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0.0 0.0 0.0" rpy="-${pi/2} 0.0 0.0" />
        <geometry>
          <!-- TODO cheange when models ready -->
          <!-- <mesh
          filename="package://${wheel_config['mesh_package']}/${wheel_config['folder_path']}/${prefix}_wheel.dae"
          /> -->
          <cylinder radius="${wheel_config['wheel_radius']}" length="${wheel_config['wheel_width']}" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="-${pi/2} 0.0 0.0" />
        <geometry>
          <cylinder radius="${wheel_config['wheel_radius']}" length="${wheel_config['wheel_width']}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0.0 ${inertia_y_offset} 0.0" rpy="0.0 0.0 0.0" />
        <mass value="${wheel_config['mass']}" />
        <inertia
          ixx="${wheel_config['inertia']['ixx']}"
          ixy="0.0"
          ixz="0.0"
          iyy="${wheel_config['inertia']['iyy']}"
          iyz="0.0"
          izz="${wheel_config['inertia']['izz']}" />
      </inertial>
    </link>

  </xacro:macro>

</robot>
