repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        # mesh files has to be taken into account
        args: ["--maxkb=3000"]
      - id: check-ast
      - id: check-json
        # vscode .json files do not follow the standard JSON format
        exclude: ^.vscode/
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: name-tests-test
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.6
    hooks:
      - id: clang-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell
        args:
          [
            "--exclude-file=panther_hardware_interfaces/config/roboteq_motor_controllers_v80_21a.eds",
            "--ignore-words-list",
            "ned" # north, east, down (NED)
          ]
        exclude_types: [rst]
        language: python
        types: [text]

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        files: ^.github|./\.yaml
        args: [--mapping, '2', --sequence, '4', --offset, '2', --width, '100']

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--line-length=99"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args:
          ["--ignore=E501,W503"] # ignore too long line and line break before binary operator,
          # black checks it

  - repo: local
    hooks:
      - id: ament_copyright
        name: ament_copyright
        description: Check if copyright notice is available in all files.
        stages: [commit]
        entry: ament_copyright
        language: system

    # Docs - RestructuredText hooks
  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
        args: ["--max-line-length=100", "--ignore=D001"]
        exclude: ^.*\/CHANGELOG\.rst/.*$

  - repo: https://github.com/tier4/pre-commit-hooks-ros
    rev: v0.8.0
    hooks:
      - id: prettier-package-xml
      - id: sort-package-xml
