ImuFilterNodelet:
  gain: 0.1
  zeta: 0.0
  mag_bias_x: 0.0
  mag_bias_y: 0.0
  mag_bias_z: 0.0
  orientation_stddev: 1e-2
  publish_tf: false
  use_mag: false
  use_magnetic_field_msg: true # If set to true, subscribe to the /imu/mag topic as a sensor_msgs/MagneticField; if set to false (deprecated), use geometry_msgs/Vector3Stamped. Only changes type of the message, whether mag data is used is controlled by the use_mag parameter
  fixed_frame: imu_link
  stateless: false
  remove_gravity_vector: false

PhidgetsSpatialNodelet:
  data_interval_ms: 8 # supported data rates: 4 8 16 24 32 40 ... 1000 (in ms)
  publish_rate: 100.0 # optional param publish_rate, defaults to 0
  # serial: 123456  # optional param serial, default is -1
  # hub_port: 0 # optional param hub_port, used if connected to a VINT hub
  # frame_id: imu_link  # optional param frame_id, default is "imu_link"
  # stdev values from imu specification (https://www.phidgets.com/?tier=3&catid=10&pcid=8&prodid=1205)
  linear_acceleration_stdev: 3.5e-3   # Currently used IMU specification 10 * (2mg ± 1.5mg) (Accelerometer Drift Max ± Accelerometer Noise for 100 Hz)
  angular_velocity_stdev: 1.5e-2      # Currently used IMU specification 0.1°/s ± 0.05°/s (Gyroscope Drift Max ± Gyroscope Noise for 100 Hz)
  # magnetic_field_stdev: 10.0          # Currently used IMU specification ± 10mG (± Magnetometer Noise)

  # compass correction params (see http://www.phidgets.com/docs/1044_User_Guide)
  # cc_mag_field: 0.52859
  # cc_offset0: 0.03921
  # cc_offset1: 0.19441
  # cc_offset2: -0.03493
  # cc_gain0: 1.81704
  # cc_gain1: 1.81028
  # cc_gain2: 2.04819
  # cc_t0: 0.00142
  # cc_t1: -0.03591
  # cc_t2: 0.00160
  # cc_t3: -0.05038
  # cc_t4: -0.03942
  # cc_t5: -0.05673
