can_interface: panther_can
odom_frame: odom
base_link_frame: base_link
publish_tf: true
publish_odom: true
publish_pose: false
publish_joints: true
motor_torque_constant: 2.6149
gear_ratio: 30.08
encoder_resolution: 1600 # 400 * 4
robot_length: 0.44

# velocity smoother params
max_vel_x: 2.0
max_vel_y: 2.0
max_vel_theta: 3.3
acc_lim_x: 1.0
acc_lim_y: 1.0
acc_lim_theta: 1.0
decel_lim_x: 4.0
decel_lim_y: 4.0
decel_lim_theta: 3.14
emergency_decel_lim_x: 8.0
emergency_decel_lim_y: 8.0
emergency_decel_lim_theta: 6.24