wheel_radius: 0.127
wheel_width: 0.09
wheel_separation: 0.45
mass: 2.0
inertia: { ixx: 0.022510, iyy: 0.034850, izz: 0.022510 }
inertia_y_offset: 0.0
mesh_package: panther_mini_description
folder_path: meshes/WH05
