joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50.0

panther_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['fl_wheel_joint', 'rl_wheel_joint']
  right_wheel: ['fr_wheel_joint', 'rr_wheel_joint']
  publish_rate: 50.0
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]

  base_frame_id: 'base_link'
  enable_odom_tf: true
  cmd_vel_timeout: 0.2

  wheel_separation            : 0.697 
  wheel_separation_multiplier : 1.0
  wheel_radius                : 0.1825
  wheel_radius_multiplier     : 1.0

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 25.0   # rad/s^2