
components:
  - type: WCH01
    parent_link: lights_channel_1_link
    xyz: -0.02 0.0 -0.0185
    rpy: 0.0 0.0 0.0
    device_namespace: wireless_charger

  # - type: WCH02
  #   parent_link: world
  #   xyz: 3.0 -2.0 1.0
  #   rpy: -1.57  0.0 1.57
  #   device_namespace: wireless_charger

  - type: CAM01
    name: camera
    parent_link: lights_channel_1_link
    xyz: 0.05 0.0 0.0
    rpy: 0.0 0.0 0.0
    device_namespace: camera
