wheel_radius: 0.1016
wheel_separation: 0.6785
mass: 2.4
inertia: {ixx: 0.010050, iyy: 0.016496, izz: 0.010068}
inertia_y_offset: 0.0
mesh_package: panther_description
folder_path: meshes/WH02
kinematics: mecanum