wheel_radius: 0.1016
wheel_width: 0.08
wheel_separation: 0.6785
mass: 2.4
inertia: { ixx: 0.010050, iyy: 0.016496, izz: 0.010068 }
inertia_y_offset: 0.0
mesh_package: panther_description
folder_path: meshes/WH02

# Selected intuitively based on WH01 results
odom_stderr: { vel_x: 3.2e-3, vel_y: 3.2e-3, vel_yaw: 8.5e-3 }
