wheel_radius: 0.1016
wheel_separation: 0.6785
mass: 2.4
inertia: { ixx: 0.010050, iyy: 0.016496, izz: 0.010068 }
inertia_y_offset: 0.0
mesh_package: panther_description
folder_path: meshes/WH02
kinematics: mecanum

velocity_x_stderr: 3.2e-3
velocity_y_stderr: 3.2e-3
velocity_yaw_stderr: 8.5e-3