---
name: Release project

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version, must match release candidate version. IMPORTANT - required format
          `X.X.X`, (e.g. `2.0.1`).
        required: true
      date:
        description: Release date stamp, must match release candidate date. IMPORTANT - required format
          `YYYYMMDD`, (e.g. `20240430`).
        required: true
      release_name:
        description: Name of the release to be created. Version in the first place is recommended (e.g.
          `2.0.1-alpha`).
        required: true
      automatic_mode:
        type: boolean
        default: false
        description: Automatically merge PRs, create releases and build images.
      prerelease:
        type: boolean
        default: false
        description: Mark the release as a prerelease.

env:
  RC_BRANCH_NAME: ${{ github.event.inputs.version }}-${{ github.event.inputs.date }}
  MAIN_BRANCH: ros2

jobs:
  release_project:
    name: Release Husarion UGV project
    runs-on: ubuntu-22.04
    steps:
      - name: Release panther_msgs repository
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: husarion
          repo: panther_msgs
          github_token: ${{ secrets.GH_PAT }}
          workflow_file_name: release-repository.yaml
          ref: ${{ env.RC_BRANCH_NAME }}
          client_payload: |
            {
              "release_candidate": "${{ env.RC_BRANCH_NAME }}",
              "version": "${{ github.event.inputs.version }}",
              "release_name": "${{ github.event.inputs.release_name }}",
              "automatic_mode": "${{ github.event.inputs.automatic_mode }}",
              "prerelease": "${{ github.event.inputs.prerelease }}"
            }

      - name: Release panther_ros repository
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: husarion
          repo: panther_ros
          github_token: ${{ secrets.GITHUB_TOKEN }} # Use the default GITHUB_TOKEN for local repository
          workflow_file_name: release-repository.yaml
          ref: ${{ env.RC_BRANCH_NAME }}
          client_payload: |
            {
              "release_candidate": "${{ env.RC_BRANCH_NAME }}",
              "version": "${{ github.event.inputs.version }}",
              "release_name": "${{ github.event.inputs.release_name }}",
              "automatic_mode": "${{ github.event.inputs.automatic_mode }}",
              "prerelease": "${{ github.event.inputs.prerelease }}"
            }

      - name: Rebuild panther docker images with new version
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: husarion
          repo: panther-docker
          github_token: ${{ secrets.GH_PAT }}
          workflow_file_name: ros-docker-image.yaml
          ref: ${{ env.RC_BRANCH_NAME }}
          client_payload: |
            {
              "panther_codebase_version": "${{ github.event.inputs.version }}",
              "build_type": "development",
              "target_distro": "humble"
            }

      - name: Release panther-docker repository
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: husarion
          repo: panther-docker
          github_token: ${{ secrets.GH_PAT }}
          workflow_file_name: release-repository.yaml
          ref: ${{ env.RC_BRANCH_NAME }}
          client_payload: |
            {
              "release_candidate": "${{ env.RC_BRANCH_NAME }}",
              "version": "${{ github.event.inputs.version }}",
              "release_name": "${{ github.event.inputs.release_name }}",
              "automatic_mode": "${{ github.event.inputs.automatic_mode }}",
              "prerelease": "${{ github.event.inputs.prerelease }}"
            }

      - name: Release panther-rpi-os-img repository
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: husarion
          repo: panther-rpi-os-img
          github_token: ${{ secrets.GH_PAT }}
          workflow_file_name: release-repository.yaml
          ref: ${{ env.RC_BRANCH_NAME }}
          client_payload: |
            {
              "release_candidate": "${{ env.RC_BRANCH_NAME }}",
              "version": "${{ github.event.inputs.version }}",
              "release_name": "${{ github.event.inputs.release_name }}",
              "automatic_mode": "${{ github.event.inputs.automatic_mode }}",
              "prerelease": "${{ github.event.inputs.prerelease }}"
            }

      - name: Build panther system image
        if: ${{ fromJSON(github.event.inputs.automatic_mode) == true }}
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: husarion
          repo: panther-rpi-os-img
          github_token: ${{ secrets.GH_PAT }}
          workflow_file_name: build_and_deploy_image.yaml
          ref: ${{ env.MAIN_BRANCH }}
          client_payload: |
            {
              "dev_image": "false",
              "panther_codebase_version": "${{ github.event.inputs.version }}",
              "image_tag": "${{ github.event.inputs.version }}"
            }

      - name: Build panther flash OS image
        if: ${{ fromJSON(github.event.inputs.automatic_mode) == true }}
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: husarion
          repo: panther-rpi-os-img
          github_token: ${{ secrets.GH_PAT }}
          workflow_file_name: build_and_deploy_flash_os_image.yaml
          ref: ${{ env.MAIN_BRANCH }}
          client_payload: |
            {
              "image_tag": "${{ github.event.inputs.version }}"
            }

      - name: Trigger repository build workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: husarion
          repo: docs_new
          github_token: ${{ secrets.GH_PAT }}
          workflow_file_name: build.yml
          ref: master
