---
name: Release candidate

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release candidate version (format `X.X.X`, e.g. `2.0.1`).
        required: true
      date:
        description: Release candidate date stamp (format `YYYYMMDD`, e.g. `20240430`).
        required: true

env:
  RC_BRANCH_NAME: ${{ github.event.inputs.version }}-${{ github.event.inputs.date }}

jobs:

  check_docs:
    name: Check docs build
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger repository build workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: husarion
          repo: docs_new
          github_token: ${{ secrets.GH_PAT }}
          workflow_file_name: test-release.yml
          ref: add-workflow-call
          wait_interval: 10
          client_payload: |
            {
              "husarion_ugv_branch": ros2-devel,
            }
