---
name: Test before release

on:
    pull_request:
    workflow_dispatch:
        inputs:
            target_branch:
                description: Target branch for the release.
                required: true

jobs:
    # TODO: Add unit testing for panther_ros when ready

    build_and_push_docker_images:
        name: Build panther docker images
        runs-on: ubuntu-22.04
        steps:
            - name: Trigger repository build workflow
              uses: convictional/trigger-workflow-and-wait@v1.6.1
              with:
                  owner: husarion
                  repo: panther-docker
                  github_token: ${{ secrets.GH_PAT }}
                  workflow_file_name: ros-docker-image.yaml
                  ref: ros2-automatize-release-process #${{ github.event.inputs.target_branch }}
                  wait_interval: 10
                  client_payload: |
                      {
                        "build_type": "development",
                        "target_distro": "humble",
                      }

    # release_panther_rpi_os_image:
    #     name: Release panther-rpi-os-image repository
    #     needs:
    #         - release_panther_docker
    #     runs-on: ubuntu-22.04
    #     steps:
    #         - name: Trigger repository release workflow
    #           uses: convictional/trigger-workflow-and-wait@v1.6.1
    #           with:
    #               owner: husarion
    #               repo: panther-rpi-os-image
    #               github_token: ${{ secrets.GH_PAT }}
    #               workflow_file_name: release-repository.yaml
    #               ref: ros2-automatize-release-process #${{ github.event.inputs.target_branch }}
    #               wait_interval: 10
    #               client_payload: |
    #                   {
    #                     "target_branch": "${{ github.event.inputs.target_branch }}",
    #                     "version": "${{ github.event.inputs.version }}",
    #                     "release_name": "${{ github.event.inputs.release_name }}",
    #                     "automatic_mode": ${{ github.event.inputs.automatic_mode }},
    #                     "prerelease": ${{ github.event.inputs.prerelease }}
    #                   }

    # build_and_publish_rpi_image:
    #     name: Build panther docker images
    #     needs:
    #         - release_panther_rpi_os_image
    #     runs-on: ubuntu-22.04
    #     steps:
    #         - name: Trigger repository build workflow
    #           uses: convictional/trigger-workflow-and-wait@v1.6.1
    #           with:
    #               owner: husarion
    #               repo: panther-rpi-os-image
    #               github_token: ${{ secrets.GH_PAT }}
    #               workflow_file_name: build_and_deploy_image.yaml
    #               ref: ros2-automatize-release-process #${{ github.event.inputs.target_branch }}
    #               wait_interval: 10
    #               client_payload: |
    #                   {
    #                     "dev_image": "false",
    #                     "panther_codebase_version": "${{ github.event.inputs.version }}",
    #                     "image_tag": "${{ github.event.inputs.release_name }}",
    #                   }
