---
name: Test before release

on:
    workflow_dispatch:
        inputs:
            target_branch:
                description: Target branch for the release.
                required: true
            test_tag:
                description: Test tag name (used for images tagging).
                required: true

jobs:
    # TODO: Add unit testing for panther_ros when ready
    unit_test_panther_ros:
        name: Run unit tests for panther_ros
        runs-on: ubuntu-22.04
        steps:
            - name: Trigger repository build workflow
              run: echo "Unit tests for panther_ros are not fully implemented yet -> SKIPPING!"

    prepare_test_branches_ros:
        name: Prepare test branch for ROS repositories
        runs-on: ubuntu-22.04
        needs:
            - unit_test_panther_ros
        strategy:
            matrix:
                repo: [panther_ros, panther_msgs]
        steps:
            - name: Create test branch
              uses: GuillaumeFalourd/create-other-repo-branch-action@v1.5
              with:
                  repository_owner: husarion
                  repository_name: ${{ matrix.repo }}
                  new_branch_name: ${{ github.event.inputs.test_tag }}
                  new_branch_ref: ${{ github.event.inputs.target_branch }}
                  access_token: ${{ secrets.GH_PAT}}

    prepare_test_branch_docker:
        name: Prepare branch with test compose
        runs-on: ubuntu-22.04
        needs:
            - unit_test_panther_ros
        steps:
            - name: Trigger repository build workflow
              uses: convictional/trigger-workflow-and-wait@v1.6.1
              with:
                  owner: husarion
                  repo: panther-docker
                  github_token: ${{ secrets.GH_PAT }}
                  workflow_file_name: prepare-test-branch.yaml
                  ref: ros2-automatize-release-process #${{ github.event.inputs.target_branch }}
                  wait_interval: 10
                  # change target branch to ${{ github.event.inputs.target_branch }}
                  client_payload: |
                      {
                        "target_branch": "ros2-automatize-release-process",
                        "test_branch": "${{ github.event.inputs.test_tag }}"
                      }

    build_and_push_docker_images:
        name: Build panther docker images
        runs-on: ubuntu-22.04
        needs:
            - prepare_test_branch_docker
        steps:
            - name: Trigger repository build workflow
              uses: convictional/trigger-workflow-and-wait@v1.6.1
              with:
                  owner: husarion
                  repo: panther-docker
                  github_token: ${{ secrets.GH_PAT }}
                  workflow_file_name: ros-docker-image.yaml
                  ref: ros2-automatize-release-process #${{ github.event.inputs.test_tag }}
                  wait_interval: 10
                  client_payload: |
                      {
                        "build_type": "development",
                        "target_distro": "humble"
                      }

    build_and_publish_rpi_image:
        name: Build panther docker images
        needs:
            - prepare_test_branches_ros
            - build_and_push_docker_images
        runs-on: ubuntu-22.04
        steps:
            - name: Trigger repository build workflow
              uses: convictional/trigger-workflow-and-wait@v1.6.1
              with:
                  owner: husarion
                  repo: panther-rpi-os-image
                  github_token: ${{ secrets.GH_PAT }}
                  workflow_file_name: build_and_deploy_image.yaml
                  ref: ros2-automatize-release-process #${{ github.event.inputs.target_branch }}
                  wait_interval: 10
                  client_payload: |
                      {
                        "dev_image": "true",
                        "panther_codebase_version": "${{ github.event.inputs.test_tag }}",
                        "image_tag": "${{ github.event.inputs.test_tag }}",
                      }

    delete_test_branches:
        name: Delete test branches
        runs-on: ubuntu-22.04
        needs:
            - build_and_publish_rpi_image
        strategy:
            matrix:
                repo: [panther_ros, panther_msgs, panther-docker]
        steps:
            - name: Delete test branch
              uses: dawidd6/action-delete-branch@v3
              with:
                  owner: husarion
                  repository: ${{ matrix.repo }}
                  branches: ${{ github.event.inputs.test_tag }}
                  github_token: ${{ secrets.GH_PAT}}
